{extends file="base.tpl"}



{block name="content" }
  
  <marquee  scrolldelay="1" scrollamount="4" direction="left" loop="infinite" onmouseout="this.start()" onmouseover="this.stop()">
<a href="{$img}foto1.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada" src="{$img}foto1.jpg" height ="250px" width="300px"/></a>
<a href="{$img}foto2.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto2.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto3.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto3.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto4.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto4.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto5.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto5.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto6.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto6.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto7.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto7.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto8.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto8.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto13.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto13.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto14.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto14.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto15.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto15.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto16.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto16.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto17.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto17.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto18.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto18.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto19.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto19.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto20.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto20.jpg" height ="250px" width="300px" /></a>
<a href="{$img}foto21.jpg" target="_blank"><img title="Titulo de la entrada" alt="Titulo de la entrada"  src="{$img}foto21.jpg" height ="250px" width="300px" /></a>

  </marquee>


<div class="panel panel-default" style="background:#819FF7">
  <div class="panel-heading" style="background:#0404B4" > 
    <h3 class="panel-title"  ><H4><FONT FACE="COOPER BLACK"  style="color:#FFFF00" >VEP EVENTS</FONT><H4></h3>
  </div>
  <div class="panel-body" style="color:#000000">
    <H4><FONT FACE="COOPER BLACK">  Founded on May 2013 by son Pascual and Mother Victoria Pellegrino,  Vep Events is where you walk through the door you are immediately transported into a land of ‘possible dreams’, you get a sense of quality, luxury and capability, for achieving the best goods and services for any event. VEP Events Lewisville's newest and most elegant Ballroom. At VEP Events select from our catalog the arrangement you wish or let us know if you need something special so we can make your dream come true. Our experts will help you make you're especial day Bright just like our motto of "Where You are the Start!!!"  </FONT><H4>
  </div>
</div>



{/block}


